// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerInfo.proto

package com.zx.demo.msg;

public final class GCPlayerInfo {
  private GCPlayerInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.PlayerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 rid = 1;</code>
     */
    boolean hasRid();
    /**
     * <code>required int64 rid = 1;</code>
     */
    long getRid();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 level = 3;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 3;</code>
     */
    int getLevel();

    /**
     * <code>required int32 exp = 4;</code>
     */
    boolean hasExp();
    /**
     * <code>required int32 exp = 4;</code>
     */
    int getExp();

    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    java.util.List<com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero> 
        getHerosList();
    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero getHeros(int index);
    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    int getHerosCount();
    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    java.util.List<? extends com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder> 
        getHerosOrBuilderList();
    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder getHerosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code demo.PlayerInfo}
   */
  public  static final class PlayerInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.PlayerInfo)
      PlayerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerInfo.newBuilder() to construct.
    private PlayerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerInfo() {
      rid_ = 0L;
      name_ = "";
      level_ = 0;
      exp_ = 0;
      heros_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              rid_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              level_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              exp_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                heros_ = new java.util.ArrayList<com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero>();
                mutable_bitField0_ |= 0x00000010;
              }
              heros_.add(
                  input.readMessage(com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          heros_ = java.util.Collections.unmodifiableList(heros_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zx.demo.msg.GCPlayerInfo.PlayerInfo.class, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Builder.class);
    }

    /**
     * Protobuf enum {@code demo.PlayerInfo.HeroType}
     */
    public enum HeroType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>COMMON = 1;</code>
       */
      COMMON(1),
      /**
       * <code>GOD = 2;</code>
       */
      GOD(2),
      ;

      /**
       * <code>COMMON = 1;</code>
       */
      public static final int COMMON_VALUE = 1;
      /**
       * <code>GOD = 2;</code>
       */
      public static final int GOD_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static HeroType valueOf(int value) {
        return forNumber(value);
      }

      public static HeroType forNumber(int value) {
        switch (value) {
          case 1: return COMMON;
          case 2: return GOD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<HeroType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          HeroType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<HeroType>() {
              public HeroType findValueByNumber(int number) {
                return HeroType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zx.demo.msg.GCPlayerInfo.PlayerInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final HeroType[] VALUES = values();

      public static HeroType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private HeroType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:demo.PlayerInfo.HeroType)
    }

    public interface HeroOrBuilder extends
        // @@protoc_insertion_point(interface_extends:demo.PlayerInfo.Hero)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required string id = 1;</code>
       */
      java.lang.String getId();
      /**
       * <code>required string id = 1;</code>
       */
      com.google.protobuf.ByteString
          getIdBytes();

      /**
       * <code>required string name = 2;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 2;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 2;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>required bool isFight = 3;</code>
       */
      boolean hasIsFight();
      /**
       * <code>required bool isFight = 3;</code>
       */
      boolean getIsFight();

      /**
       * <code>required int32 skill = 4;</code>
       */
      boolean hasSkill();
      /**
       * <code>required int32 skill = 4;</code>
       */
      int getSkill();

      /**
       * <code>required int32 level = 5;</code>
       */
      boolean hasLevel();
      /**
       * <code>required int32 level = 5;</code>
       */
      int getLevel();

      /**
       * <code>required .demo.PlayerInfo.HeroType type = 6 [default = COMMON];</code>
       */
      boolean hasType();
      /**
       * <code>required .demo.PlayerInfo.HeroType type = 6 [default = COMMON];</code>
       */
      com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType getType();

      /**
       * <code>optional string extra = 7;</code>
       */
      boolean hasExtra();
      /**
       * <code>optional string extra = 7;</code>
       */
      java.lang.String getExtra();
      /**
       * <code>optional string extra = 7;</code>
       */
      com.google.protobuf.ByteString
          getExtraBytes();
    }
    /**
     * Protobuf type {@code demo.PlayerInfo.Hero}
     */
    public  static final class Hero extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:demo.PlayerInfo.Hero)
        HeroOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Hero.newBuilder() to construct.
      private Hero(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Hero() {
        id_ = "";
        name_ = "";
        isFight_ = false;
        skill_ = 0;
        level_ = 0;
        type_ = 1;
        extra_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Hero(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                id_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                name_ = bs;
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                isFight_ = input.readBool();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                skill_ = input.readInt32();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                level_ = input.readInt32();
                break;
              }
              case 48: {
                int rawValue = input.readEnum();
                  @SuppressWarnings("deprecation")
                com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType value = com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(6, rawValue);
                } else {
                  bitField0_ |= 0x00000020;
                  type_ = rawValue;
                }
                break;
              }
              case 58: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000040;
                extra_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_Hero_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_Hero_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.class, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder.class);
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private volatile java.lang.Object id_;
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object name_;
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ISFIGHT_FIELD_NUMBER = 3;
      private boolean isFight_;
      /**
       * <code>required bool isFight = 3;</code>
       */
      public boolean hasIsFight() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool isFight = 3;</code>
       */
      public boolean getIsFight() {
        return isFight_;
      }

      public static final int SKILL_FIELD_NUMBER = 4;
      private int skill_;
      /**
       * <code>required int32 skill = 4;</code>
       */
      public boolean hasSkill() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 skill = 4;</code>
       */
      public int getSkill() {
        return skill_;
      }

      public static final int LEVEL_FIELD_NUMBER = 5;
      private int level_;
      /**
       * <code>required int32 level = 5;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 level = 5;</code>
       */
      public int getLevel() {
        return level_;
      }

      public static final int TYPE_FIELD_NUMBER = 6;
      private int type_;
      /**
       * <code>required .demo.PlayerInfo.HeroType type = 6 [default = COMMON];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .demo.PlayerInfo.HeroType type = 6 [default = COMMON];</code>
       */
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType getType() {
        @SuppressWarnings("deprecation")
        com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType result = com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType.valueOf(type_);
        return result == null ? com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType.COMMON : result;
      }

      public static final int EXTRA_FIELD_NUMBER = 7;
      private volatile java.lang.Object extra_;
      /**
       * <code>optional string extra = 7;</code>
       */
      public boolean hasExtra() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string extra = 7;</code>
       */
      public java.lang.String getExtra() {
        java.lang.Object ref = extra_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            extra_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string extra = 7;</code>
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        java.lang.Object ref = extra_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasIsFight()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSkill()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLevel()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBool(3, isFight_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, skill_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeInt32(5, level_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeEnum(6, type_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 7, extra_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, isFight_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, skill_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, level_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(6, type_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, extra_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero)) {
          return super.equals(obj);
        }
        com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero other = (com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero) obj;

        boolean result = true;
        result = result && (hasId() == other.hasId());
        if (hasId()) {
          result = result && getId()
              .equals(other.getId());
        }
        result = result && (hasName() == other.hasName());
        if (hasName()) {
          result = result && getName()
              .equals(other.getName());
        }
        result = result && (hasIsFight() == other.hasIsFight());
        if (hasIsFight()) {
          result = result && (getIsFight()
              == other.getIsFight());
        }
        result = result && (hasSkill() == other.hasSkill());
        if (hasSkill()) {
          result = result && (getSkill()
              == other.getSkill());
        }
        result = result && (hasLevel() == other.hasLevel());
        if (hasLevel()) {
          result = result && (getLevel()
              == other.getLevel());
        }
        result = result && (hasType() == other.hasType());
        if (hasType()) {
          result = result && type_ == other.type_;
        }
        result = result && (hasExtra() == other.hasExtra());
        if (hasExtra()) {
          result = result && getExtra()
              .equals(other.getExtra());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasId()) {
          hash = (37 * hash) + ID_FIELD_NUMBER;
          hash = (53 * hash) + getId().hashCode();
        }
        if (hasName()) {
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
        }
        if (hasIsFight()) {
          hash = (37 * hash) + ISFIGHT_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getIsFight());
        }
        if (hasSkill()) {
          hash = (37 * hash) + SKILL_FIELD_NUMBER;
          hash = (53 * hash) + getSkill();
        }
        if (hasLevel()) {
          hash = (37 * hash) + LEVEL_FIELD_NUMBER;
          hash = (53 * hash) + getLevel();
        }
        if (hasType()) {
          hash = (37 * hash) + TYPE_FIELD_NUMBER;
          hash = (53 * hash) + type_;
        }
        if (hasExtra()) {
          hash = (37 * hash) + EXTRA_FIELD_NUMBER;
          hash = (53 * hash) + getExtra().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code demo.PlayerInfo.Hero}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:demo.PlayerInfo.Hero)
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_Hero_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_Hero_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.class, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder.class);
        }

        // Construct using com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          isFight_ = false;
          bitField0_ = (bitField0_ & ~0x00000004);
          skill_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          level_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          type_ = 1;
          bitField0_ = (bitField0_ & ~0x00000020);
          extra_ = "";
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_Hero_descriptor;
        }

        @java.lang.Override
        public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero getDefaultInstanceForType() {
          return com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.getDefaultInstance();
        }

        @java.lang.Override
        public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero build() {
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero buildPartial() {
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero result = new com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.isFight_ = isFight_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.skill_ = skill_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.level_ = level_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.extra_ = extra_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero) {
            return mergeFrom((com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero other) {
          if (other == com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.getDefaultInstance()) return this;
          if (other.hasId()) {
            bitField0_ |= 0x00000001;
            id_ = other.id_;
            onChanged();
          }
          if (other.hasName()) {
            bitField0_ |= 0x00000002;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasIsFight()) {
            setIsFight(other.getIsFight());
          }
          if (other.hasSkill()) {
            setSkill(other.getSkill());
          }
          if (other.hasLevel()) {
            setLevel(other.getLevel());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasExtra()) {
            bitField0_ |= 0x00000040;
            extra_ = other.extra_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasId()) {
            return false;
          }
          if (!hasName()) {
            return false;
          }
          if (!hasIsFight()) {
            return false;
          }
          if (!hasSkill()) {
            return false;
          }
          if (!hasLevel()) {
            return false;
          }
          if (!hasType()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object id_ = "";
        /**
         * <code>required string id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string id = 1;</code>
         */
        public java.lang.String getId() {
          java.lang.Object ref = id_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              id_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getIdBytes() {
          java.lang.Object ref = id_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            id_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }
        /**
         * <code>required string id = 1;</code>
         */
        public Builder setIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 2;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string name = 2;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 2;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 2;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 2;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }

        private boolean isFight_ ;
        /**
         * <code>required bool isFight = 3;</code>
         */
        public boolean hasIsFight() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required bool isFight = 3;</code>
         */
        public boolean getIsFight() {
          return isFight_;
        }
        /**
         * <code>required bool isFight = 3;</code>
         */
        public Builder setIsFight(boolean value) {
          bitField0_ |= 0x00000004;
          isFight_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool isFight = 3;</code>
         */
        public Builder clearIsFight() {
          bitField0_ = (bitField0_ & ~0x00000004);
          isFight_ = false;
          onChanged();
          return this;
        }

        private int skill_ ;
        /**
         * <code>required int32 skill = 4;</code>
         */
        public boolean hasSkill() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required int32 skill = 4;</code>
         */
        public int getSkill() {
          return skill_;
        }
        /**
         * <code>required int32 skill = 4;</code>
         */
        public Builder setSkill(int value) {
          bitField0_ |= 0x00000008;
          skill_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 skill = 4;</code>
         */
        public Builder clearSkill() {
          bitField0_ = (bitField0_ & ~0x00000008);
          skill_ = 0;
          onChanged();
          return this;
        }

        private int level_ ;
        /**
         * <code>required int32 level = 5;</code>
         */
        public boolean hasLevel() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required int32 level = 5;</code>
         */
        public int getLevel() {
          return level_;
        }
        /**
         * <code>required int32 level = 5;</code>
         */
        public Builder setLevel(int value) {
          bitField0_ |= 0x00000010;
          level_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 level = 5;</code>
         */
        public Builder clearLevel() {
          bitField0_ = (bitField0_ & ~0x00000010);
          level_ = 0;
          onChanged();
          return this;
        }

        private int type_ = 1;
        /**
         * <code>required .demo.PlayerInfo.HeroType type = 6 [default = COMMON];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required .demo.PlayerInfo.HeroType type = 6 [default = COMMON];</code>
         */
        public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType getType() {
          @SuppressWarnings("deprecation")
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType result = com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType.valueOf(type_);
          return result == null ? com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType.COMMON : result;
        }
        /**
         * <code>required .demo.PlayerInfo.HeroType type = 6 [default = COMMON];</code>
         */
        public Builder setType(com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000020;
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required .demo.PlayerInfo.HeroType type = 6 [default = COMMON];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000020);
          type_ = 1;
          onChanged();
          return this;
        }

        private java.lang.Object extra_ = "";
        /**
         * <code>optional string extra = 7;</code>
         */
        public boolean hasExtra() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional string extra = 7;</code>
         */
        public java.lang.String getExtra() {
          java.lang.Object ref = extra_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              extra_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string extra = 7;</code>
         */
        public com.google.protobuf.ByteString
            getExtraBytes() {
          java.lang.Object ref = extra_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            extra_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string extra = 7;</code>
         */
        public Builder setExtra(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          extra_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string extra = 7;</code>
         */
        public Builder clearExtra() {
          bitField0_ = (bitField0_ & ~0x00000040);
          extra_ = getDefaultInstance().getExtra();
          onChanged();
          return this;
        }
        /**
         * <code>optional string extra = 7;</code>
         */
        public Builder setExtraBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          extra_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:demo.PlayerInfo.Hero)
      }

      // @@protoc_insertion_point(class_scope:demo.PlayerInfo.Hero)
      private static final com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero();
      }

      public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Hero>
          PARSER = new com.google.protobuf.AbstractParser<Hero>() {
        @java.lang.Override
        public Hero parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Hero(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Hero> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Hero> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int RID_FIELD_NUMBER = 1;
    private long rid_;
    /**
     * <code>required int64 rid = 1;</code>
     */
    public boolean hasRid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 rid = 1;</code>
     */
    public long getRid() {
      return rid_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>required int32 level = 3;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 level = 3;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int EXP_FIELD_NUMBER = 4;
    private int exp_;
    /**
     * <code>required int32 exp = 4;</code>
     */
    public boolean hasExp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 exp = 4;</code>
     */
    public int getExp() {
      return exp_;
    }

    public static final int HEROS_FIELD_NUMBER = 5;
    private java.util.List<com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero> heros_;
    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    public java.util.List<com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero> getHerosList() {
      return heros_;
    }
    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    public java.util.List<? extends com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder> 
        getHerosOrBuilderList() {
      return heros_;
    }
    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    public int getHerosCount() {
      return heros_.size();
    }
    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero getHeros(int index) {
      return heros_.get(index);
    }
    /**
     * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
     */
    public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder getHerosOrBuilder(
        int index) {
      return heros_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getHerosCount(); i++) {
        if (!getHeros(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, exp_);
      }
      for (int i = 0; i < heros_.size(); i++) {
        output.writeMessage(5, heros_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, exp_);
      }
      for (int i = 0; i < heros_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, heros_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zx.demo.msg.GCPlayerInfo.PlayerInfo)) {
        return super.equals(obj);
      }
      com.zx.demo.msg.GCPlayerInfo.PlayerInfo other = (com.zx.demo.msg.GCPlayerInfo.PlayerInfo) obj;

      boolean result = true;
      result = result && (hasRid() == other.hasRid());
      if (hasRid()) {
        result = result && (getRid()
            == other.getRid());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasLevel() == other.hasLevel());
      if (hasLevel()) {
        result = result && (getLevel()
            == other.getLevel());
      }
      result = result && (hasExp() == other.hasExp());
      if (hasExp()) {
        result = result && (getExp()
            == other.getExp());
      }
      result = result && getHerosList()
          .equals(other.getHerosList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRid()) {
        hash = (37 * hash) + RID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRid());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasLevel()) {
        hash = (37 * hash) + LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getLevel();
      }
      if (hasExp()) {
        hash = (37 * hash) + EXP_FIELD_NUMBER;
        hash = (53 * hash) + getExp();
      }
      if (getHerosCount() > 0) {
        hash = (37 * hash) + HEROS_FIELD_NUMBER;
        hash = (53 * hash) + getHerosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zx.demo.msg.GCPlayerInfo.PlayerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.PlayerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.PlayerInfo)
        com.zx.demo.msg.GCPlayerInfo.PlayerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zx.demo.msg.GCPlayerInfo.PlayerInfo.class, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Builder.class);
      }

      // Construct using com.zx.demo.msg.GCPlayerInfo.PlayerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHerosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (herosBuilder_ == null) {
          heros_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          herosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zx.demo.msg.GCPlayerInfo.internal_static_demo_PlayerInfo_descriptor;
      }

      @java.lang.Override
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo getDefaultInstanceForType() {
        return com.zx.demo.msg.GCPlayerInfo.PlayerInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo build() {
        com.zx.demo.msg.GCPlayerInfo.PlayerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo buildPartial() {
        com.zx.demo.msg.GCPlayerInfo.PlayerInfo result = new com.zx.demo.msg.GCPlayerInfo.PlayerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rid_ = rid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.exp_ = exp_;
        if (herosBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            heros_ = java.util.Collections.unmodifiableList(heros_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.heros_ = heros_;
        } else {
          result.heros_ = herosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zx.demo.msg.GCPlayerInfo.PlayerInfo) {
          return mergeFrom((com.zx.demo.msg.GCPlayerInfo.PlayerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zx.demo.msg.GCPlayerInfo.PlayerInfo other) {
        if (other == com.zx.demo.msg.GCPlayerInfo.PlayerInfo.getDefaultInstance()) return this;
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (herosBuilder_ == null) {
          if (!other.heros_.isEmpty()) {
            if (heros_.isEmpty()) {
              heros_ = other.heros_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureHerosIsMutable();
              heros_.addAll(other.heros_);
            }
            onChanged();
          }
        } else {
          if (!other.heros_.isEmpty()) {
            if (herosBuilder_.isEmpty()) {
              herosBuilder_.dispose();
              herosBuilder_ = null;
              heros_ = other.heros_;
              bitField0_ = (bitField0_ & ~0x00000010);
              herosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getHerosFieldBuilder() : null;
            } else {
              herosBuilder_.addAllMessages(other.heros_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRid()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasLevel()) {
          return false;
        }
        if (!hasExp()) {
          return false;
        }
        for (int i = 0; i < getHerosCount(); i++) {
          if (!getHeros(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zx.demo.msg.GCPlayerInfo.PlayerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zx.demo.msg.GCPlayerInfo.PlayerInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long rid_ ;
      /**
       * <code>required int64 rid = 1;</code>
       */
      public boolean hasRid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public long getRid() {
        return rid_;
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public Builder setRid(long value) {
        bitField0_ |= 0x00000001;
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 rid = 1;</code>
       */
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>required int32 level = 3;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 level = 3;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 3;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 3;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }

      private int exp_ ;
      /**
       * <code>required int32 exp = 4;</code>
       */
      public boolean hasExp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 exp = 4;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>required int32 exp = 4;</code>
       */
      public Builder setExp(int value) {
        bitField0_ |= 0x00000008;
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 exp = 4;</code>
       */
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        exp_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero> heros_ =
        java.util.Collections.emptyList();
      private void ensureHerosIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          heros_ = new java.util.ArrayList<com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero>(heros_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder> herosBuilder_;

      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public java.util.List<com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero> getHerosList() {
        if (herosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(heros_);
        } else {
          return herosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public int getHerosCount() {
        if (herosBuilder_ == null) {
          return heros_.size();
        } else {
          return herosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero getHeros(int index) {
        if (herosBuilder_ == null) {
          return heros_.get(index);
        } else {
          return herosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public Builder setHeros(
          int index, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero value) {
        if (herosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHerosIsMutable();
          heros_.set(index, value);
          onChanged();
        } else {
          herosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public Builder setHeros(
          int index, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder builderForValue) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          heros_.set(index, builderForValue.build());
          onChanged();
        } else {
          herosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public Builder addHeros(com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero value) {
        if (herosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHerosIsMutable();
          heros_.add(value);
          onChanged();
        } else {
          herosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public Builder addHeros(
          int index, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero value) {
        if (herosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHerosIsMutable();
          heros_.add(index, value);
          onChanged();
        } else {
          herosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public Builder addHeros(
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder builderForValue) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          heros_.add(builderForValue.build());
          onChanged();
        } else {
          herosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public Builder addHeros(
          int index, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder builderForValue) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          heros_.add(index, builderForValue.build());
          onChanged();
        } else {
          herosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public Builder addAllHeros(
          java.lang.Iterable<? extends com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero> values) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, heros_);
          onChanged();
        } else {
          herosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public Builder clearHeros() {
        if (herosBuilder_ == null) {
          heros_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          herosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public Builder removeHeros(int index) {
        if (herosBuilder_ == null) {
          ensureHerosIsMutable();
          heros_.remove(index);
          onChanged();
        } else {
          herosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder getHerosBuilder(
          int index) {
        return getHerosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder getHerosOrBuilder(
          int index) {
        if (herosBuilder_ == null) {
          return heros_.get(index);  } else {
          return herosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public java.util.List<? extends com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder> 
           getHerosOrBuilderList() {
        if (herosBuilder_ != null) {
          return herosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(heros_);
        }
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder addHerosBuilder() {
        return getHerosFieldBuilder().addBuilder(
            com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder addHerosBuilder(
          int index) {
        return getHerosFieldBuilder().addBuilder(
            index, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.PlayerInfo.Hero heros = 5;</code>
       */
      public java.util.List<com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder> 
           getHerosBuilderList() {
        return getHerosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder> 
          getHerosFieldBuilder() {
        if (herosBuilder_ == null) {
          herosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Hero.Builder, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.HeroOrBuilder>(
                  heros_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          heros_ = null;
        }
        return herosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.PlayerInfo)
    }

    // @@protoc_insertion_point(class_scope:demo.PlayerInfo)
    private static final com.zx.demo.msg.GCPlayerInfo.PlayerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zx.demo.msg.GCPlayerInfo.PlayerInfo();
    }

    public static com.zx.demo.msg.GCPlayerInfo.PlayerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PlayerInfo>
        PARSER = new com.google.protobuf.AbstractParser<PlayerInfo>() {
      @java.lang.Override
      public PlayerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zx.demo.msg.GCPlayerInfo.PlayerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_PlayerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_PlayerInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_PlayerInfo_Hero_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_PlayerInfo_Hero_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PlayerInfo.proto\022\004demo\"\234\002\n\nPlayerInfo\022" +
      "\013\n\003rid\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\022\r\n\005level\030\003 \002(" +
      "\005\022\013\n\003exp\030\004 \002(\005\022$\n\005heros\030\005 \003(\0132\025.demo.Pla" +
      "yerInfo.Hero\032\217\001\n\004Hero\022\n\n\002id\030\001 \002(\t\022\014\n\004nam" +
      "e\030\002 \002(\t\022\017\n\007isFight\030\003 \002(\010\022\r\n\005skill\030\004 \002(\005\022" +
      "\r\n\005level\030\005 \002(\005\022/\n\004type\030\006 \002(\0162\031.demo.Play" +
      "erInfo.HeroType:\006COMMON\022\r\n\005extra\030\007 \001(\t\"\037" +
      "\n\010HeroType\022\n\n\006COMMON\020\001\022\007\n\003GOD\020\002B\037\n\017com.z" +
      "x.demo.msgB\014GCPlayerInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_PlayerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_PlayerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_PlayerInfo_descriptor,
        new java.lang.String[] { "Rid", "Name", "Level", "Exp", "Heros", });
    internal_static_demo_PlayerInfo_Hero_descriptor =
      internal_static_demo_PlayerInfo_descriptor.getNestedTypes().get(0);
    internal_static_demo_PlayerInfo_Hero_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_PlayerInfo_Hero_descriptor,
        new java.lang.String[] { "Id", "Name", "IsFight", "Skill", "Level", "Type", "Extra", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
