// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IMsg.proto

package com.zx.demo.msg;

public final class IMessage {
  private IMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.IMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .demo.MsgType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .demo.MsgType type = 1;</code>
     */
    com.zx.demo.msg.MessageType.MsgType getType();

    /**
     * <code>required fixed32 sequence = 2;</code>
     */
    boolean hasSequence();
    /**
     * <code>required fixed32 sequence = 2;</code>
     */
    int getSequence();

    /**
     * <code>optional .demo.IReqMsg request = 3;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .demo.IReqMsg request = 3;</code>
     */
    com.zx.demo.msg.IRequestMsg.IReqMsg getRequest();
    /**
     * <code>optional .demo.IReqMsg request = 3;</code>
     */
    com.zx.demo.msg.IRequestMsg.IReqMsgOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .demo.IRespMsg response = 4;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .demo.IRespMsg response = 4;</code>
     */
    com.zx.demo.msg.IResponseMsg.IRespMsg getResponse();
    /**
     * <code>optional .demo.IRespMsg response = 4;</code>
     */
    com.zx.demo.msg.IResponseMsg.IRespMsgOrBuilder getResponseOrBuilder();

    /**
     * <code>optional .demo.ICmdMsg commond = 5;</code>
     */
    boolean hasCommond();
    /**
     * <code>optional .demo.ICmdMsg commond = 5;</code>
     */
    com.zx.demo.msg.ICommondMsg.ICmdMsg getCommond();
    /**
     * <code>optional .demo.ICmdMsg commond = 5;</code>
     */
    com.zx.demo.msg.ICommondMsg.ICmdMsgOrBuilder getCommondOrBuilder();
  }
  /**
   * Protobuf type {@code demo.IMsg}
   */
  public  static final class IMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.IMsg)
      IMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IMsg.newBuilder() to construct.
    private IMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IMsg() {
      type_ = 1;
      sequence_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.zx.demo.msg.MessageType.MsgType value = com.zx.demo.msg.MessageType.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              sequence_ = input.readFixed32();
              break;
            }
            case 26: {
              com.zx.demo.msg.IRequestMsg.IReqMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.zx.demo.msg.IRequestMsg.IReqMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.zx.demo.msg.IResponseMsg.IRespMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.zx.demo.msg.IResponseMsg.IRespMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              com.zx.demo.msg.ICommondMsg.ICmdMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = commond_.toBuilder();
              }
              commond_ = input.readMessage(com.zx.demo.msg.ICommondMsg.ICmdMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(commond_);
                commond_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zx.demo.msg.IMessage.internal_static_demo_IMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zx.demo.msg.IMessage.internal_static_demo_IMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zx.demo.msg.IMessage.IMsg.class, com.zx.demo.msg.IMessage.IMsg.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .demo.MsgType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .demo.MsgType type = 1;</code>
     */
    public com.zx.demo.msg.MessageType.MsgType getType() {
      @SuppressWarnings("deprecation")
      com.zx.demo.msg.MessageType.MsgType result = com.zx.demo.msg.MessageType.MsgType.valueOf(type_);
      return result == null ? com.zx.demo.msg.MessageType.MsgType.REQ_PLAYER : result;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 2;
    private int sequence_;
    /**
     * <code>required fixed32 sequence = 2;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required fixed32 sequence = 2;</code>
     */
    public int getSequence() {
      return sequence_;
    }

    public static final int REQUEST_FIELD_NUMBER = 3;
    private com.zx.demo.msg.IRequestMsg.IReqMsg request_;
    /**
     * <code>optional .demo.IReqMsg request = 3;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .demo.IReqMsg request = 3;</code>
     */
    public com.zx.demo.msg.IRequestMsg.IReqMsg getRequest() {
      return request_ == null ? com.zx.demo.msg.IRequestMsg.IReqMsg.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .demo.IReqMsg request = 3;</code>
     */
    public com.zx.demo.msg.IRequestMsg.IReqMsgOrBuilder getRequestOrBuilder() {
      return request_ == null ? com.zx.demo.msg.IRequestMsg.IReqMsg.getDefaultInstance() : request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 4;
    private com.zx.demo.msg.IResponseMsg.IRespMsg response_;
    /**
     * <code>optional .demo.IRespMsg response = 4;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .demo.IRespMsg response = 4;</code>
     */
    public com.zx.demo.msg.IResponseMsg.IRespMsg getResponse() {
      return response_ == null ? com.zx.demo.msg.IResponseMsg.IRespMsg.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .demo.IRespMsg response = 4;</code>
     */
    public com.zx.demo.msg.IResponseMsg.IRespMsgOrBuilder getResponseOrBuilder() {
      return response_ == null ? com.zx.demo.msg.IResponseMsg.IRespMsg.getDefaultInstance() : response_;
    }

    public static final int COMMOND_FIELD_NUMBER = 5;
    private com.zx.demo.msg.ICommondMsg.ICmdMsg commond_;
    /**
     * <code>optional .demo.ICmdMsg commond = 5;</code>
     */
    public boolean hasCommond() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .demo.ICmdMsg commond = 5;</code>
     */
    public com.zx.demo.msg.ICommondMsg.ICmdMsg getCommond() {
      return commond_ == null ? com.zx.demo.msg.ICommondMsg.ICmdMsg.getDefaultInstance() : commond_;
    }
    /**
     * <code>optional .demo.ICmdMsg commond = 5;</code>
     */
    public com.zx.demo.msg.ICommondMsg.ICmdMsgOrBuilder getCommondOrBuilder() {
      return commond_ == null ? com.zx.demo.msg.ICommondMsg.ICmdMsg.getDefaultInstance() : commond_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed32(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getRequest());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getResponse());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getCommond());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRequest());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getResponse());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCommond());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zx.demo.msg.IMessage.IMsg)) {
        return super.equals(obj);
      }
      com.zx.demo.msg.IMessage.IMsg other = (com.zx.demo.msg.IMessage.IMsg) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasSequence() == other.hasSequence());
      if (hasSequence()) {
        result = result && (getSequence()
            == other.getSequence());
      }
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      result = result && (hasCommond() == other.hasCommond());
      if (hasCommond()) {
        result = result && getCommond()
            .equals(other.getCommond());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasSequence()) {
        hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
        hash = (53 * hash) + getSequence();
      }
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      if (hasCommond()) {
        hash = (37 * hash) + COMMOND_FIELD_NUMBER;
        hash = (53 * hash) + getCommond().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zx.demo.msg.IMessage.IMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.IMessage.IMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zx.demo.msg.IMessage.IMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.IMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.IMsg)
        com.zx.demo.msg.IMessage.IMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zx.demo.msg.IMessage.internal_static_demo_IMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zx.demo.msg.IMessage.internal_static_demo_IMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zx.demo.msg.IMessage.IMsg.class, com.zx.demo.msg.IMessage.IMsg.Builder.class);
      }

      // Construct using com.zx.demo.msg.IMessage.IMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getResponseFieldBuilder();
          getCommondFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        sequence_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (commondBuilder_ == null) {
          commond_ = null;
        } else {
          commondBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zx.demo.msg.IMessage.internal_static_demo_IMsg_descriptor;
      }

      @java.lang.Override
      public com.zx.demo.msg.IMessage.IMsg getDefaultInstanceForType() {
        return com.zx.demo.msg.IMessage.IMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.zx.demo.msg.IMessage.IMsg build() {
        com.zx.demo.msg.IMessage.IMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zx.demo.msg.IMessage.IMsg buildPartial() {
        com.zx.demo.msg.IMessage.IMsg result = new com.zx.demo.msg.IMessage.IMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sequence_ = sequence_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (commondBuilder_ == null) {
          result.commond_ = commond_;
        } else {
          result.commond_ = commondBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zx.demo.msg.IMessage.IMsg) {
          return mergeFrom((com.zx.demo.msg.IMessage.IMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zx.demo.msg.IMessage.IMsg other) {
        if (other == com.zx.demo.msg.IMessage.IMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.hasCommond()) {
          mergeCommond(other.getCommond());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasSequence()) {
          return false;
        }
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zx.demo.msg.IMessage.IMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zx.demo.msg.IMessage.IMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>required .demo.MsgType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .demo.MsgType type = 1;</code>
       */
      public com.zx.demo.msg.MessageType.MsgType getType() {
        @SuppressWarnings("deprecation")
        com.zx.demo.msg.MessageType.MsgType result = com.zx.demo.msg.MessageType.MsgType.valueOf(type_);
        return result == null ? com.zx.demo.msg.MessageType.MsgType.REQ_PLAYER : result;
      }
      /**
       * <code>required .demo.MsgType type = 1;</code>
       */
      public Builder setType(com.zx.demo.msg.MessageType.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .demo.MsgType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private int sequence_ ;
      /**
       * <code>required fixed32 sequence = 2;</code>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required fixed32 sequence = 2;</code>
       */
      public int getSequence() {
        return sequence_;
      }
      /**
       * <code>required fixed32 sequence = 2;</code>
       */
      public Builder setSequence(int value) {
        bitField0_ |= 0x00000002;
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 sequence = 2;</code>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequence_ = 0;
        onChanged();
        return this;
      }

      private com.zx.demo.msg.IRequestMsg.IReqMsg request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.IRequestMsg.IReqMsg, com.zx.demo.msg.IRequestMsg.IReqMsg.Builder, com.zx.demo.msg.IRequestMsg.IReqMsgOrBuilder> requestBuilder_;
      /**
       * <code>optional .demo.IReqMsg request = 3;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .demo.IReqMsg request = 3;</code>
       */
      public com.zx.demo.msg.IRequestMsg.IReqMsg getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.zx.demo.msg.IRequestMsg.IReqMsg.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .demo.IReqMsg request = 3;</code>
       */
      public Builder setRequest(com.zx.demo.msg.IRequestMsg.IReqMsg value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .demo.IReqMsg request = 3;</code>
       */
      public Builder setRequest(
          com.zx.demo.msg.IRequestMsg.IReqMsg.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .demo.IReqMsg request = 3;</code>
       */
      public Builder mergeRequest(com.zx.demo.msg.IRequestMsg.IReqMsg value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              request_ != null &&
              request_ != com.zx.demo.msg.IRequestMsg.IReqMsg.getDefaultInstance()) {
            request_ =
              com.zx.demo.msg.IRequestMsg.IReqMsg.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .demo.IReqMsg request = 3;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .demo.IReqMsg request = 3;</code>
       */
      public com.zx.demo.msg.IRequestMsg.IReqMsg.Builder getRequestBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .demo.IReqMsg request = 3;</code>
       */
      public com.zx.demo.msg.IRequestMsg.IReqMsgOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              com.zx.demo.msg.IRequestMsg.IReqMsg.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .demo.IReqMsg request = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.IRequestMsg.IReqMsg, com.zx.demo.msg.IRequestMsg.IReqMsg.Builder, com.zx.demo.msg.IRequestMsg.IReqMsgOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zx.demo.msg.IRequestMsg.IReqMsg, com.zx.demo.msg.IRequestMsg.IReqMsg.Builder, com.zx.demo.msg.IRequestMsg.IReqMsgOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private com.zx.demo.msg.IResponseMsg.IRespMsg response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.IResponseMsg.IRespMsg, com.zx.demo.msg.IResponseMsg.IRespMsg.Builder, com.zx.demo.msg.IResponseMsg.IRespMsgOrBuilder> responseBuilder_;
      /**
       * <code>optional .demo.IRespMsg response = 4;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .demo.IRespMsg response = 4;</code>
       */
      public com.zx.demo.msg.IResponseMsg.IRespMsg getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.zx.demo.msg.IResponseMsg.IRespMsg.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .demo.IRespMsg response = 4;</code>
       */
      public Builder setResponse(com.zx.demo.msg.IResponseMsg.IRespMsg value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .demo.IRespMsg response = 4;</code>
       */
      public Builder setResponse(
          com.zx.demo.msg.IResponseMsg.IRespMsg.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .demo.IRespMsg response = 4;</code>
       */
      public Builder mergeResponse(com.zx.demo.msg.IResponseMsg.IRespMsg value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              response_ != null &&
              response_ != com.zx.demo.msg.IResponseMsg.IRespMsg.getDefaultInstance()) {
            response_ =
              com.zx.demo.msg.IResponseMsg.IRespMsg.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .demo.IRespMsg response = 4;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .demo.IRespMsg response = 4;</code>
       */
      public com.zx.demo.msg.IResponseMsg.IRespMsg.Builder getResponseBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .demo.IRespMsg response = 4;</code>
       */
      public com.zx.demo.msg.IResponseMsg.IRespMsgOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              com.zx.demo.msg.IResponseMsg.IRespMsg.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .demo.IRespMsg response = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.IResponseMsg.IRespMsg, com.zx.demo.msg.IResponseMsg.IRespMsg.Builder, com.zx.demo.msg.IResponseMsg.IRespMsgOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zx.demo.msg.IResponseMsg.IRespMsg, com.zx.demo.msg.IResponseMsg.IRespMsg.Builder, com.zx.demo.msg.IResponseMsg.IRespMsgOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private com.zx.demo.msg.ICommondMsg.ICmdMsg commond_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.ICommondMsg.ICmdMsg, com.zx.demo.msg.ICommondMsg.ICmdMsg.Builder, com.zx.demo.msg.ICommondMsg.ICmdMsgOrBuilder> commondBuilder_;
      /**
       * <code>optional .demo.ICmdMsg commond = 5;</code>
       */
      public boolean hasCommond() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .demo.ICmdMsg commond = 5;</code>
       */
      public com.zx.demo.msg.ICommondMsg.ICmdMsg getCommond() {
        if (commondBuilder_ == null) {
          return commond_ == null ? com.zx.demo.msg.ICommondMsg.ICmdMsg.getDefaultInstance() : commond_;
        } else {
          return commondBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .demo.ICmdMsg commond = 5;</code>
       */
      public Builder setCommond(com.zx.demo.msg.ICommondMsg.ICmdMsg value) {
        if (commondBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          commond_ = value;
          onChanged();
        } else {
          commondBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .demo.ICmdMsg commond = 5;</code>
       */
      public Builder setCommond(
          com.zx.demo.msg.ICommondMsg.ICmdMsg.Builder builderForValue) {
        if (commondBuilder_ == null) {
          commond_ = builderForValue.build();
          onChanged();
        } else {
          commondBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .demo.ICmdMsg commond = 5;</code>
       */
      public Builder mergeCommond(com.zx.demo.msg.ICommondMsg.ICmdMsg value) {
        if (commondBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              commond_ != null &&
              commond_ != com.zx.demo.msg.ICommondMsg.ICmdMsg.getDefaultInstance()) {
            commond_ =
              com.zx.demo.msg.ICommondMsg.ICmdMsg.newBuilder(commond_).mergeFrom(value).buildPartial();
          } else {
            commond_ = value;
          }
          onChanged();
        } else {
          commondBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .demo.ICmdMsg commond = 5;</code>
       */
      public Builder clearCommond() {
        if (commondBuilder_ == null) {
          commond_ = null;
          onChanged();
        } else {
          commondBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .demo.ICmdMsg commond = 5;</code>
       */
      public com.zx.demo.msg.ICommondMsg.ICmdMsg.Builder getCommondBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getCommondFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .demo.ICmdMsg commond = 5;</code>
       */
      public com.zx.demo.msg.ICommondMsg.ICmdMsgOrBuilder getCommondOrBuilder() {
        if (commondBuilder_ != null) {
          return commondBuilder_.getMessageOrBuilder();
        } else {
          return commond_ == null ?
              com.zx.demo.msg.ICommondMsg.ICmdMsg.getDefaultInstance() : commond_;
        }
      }
      /**
       * <code>optional .demo.ICmdMsg commond = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.ICommondMsg.ICmdMsg, com.zx.demo.msg.ICommondMsg.ICmdMsg.Builder, com.zx.demo.msg.ICommondMsg.ICmdMsgOrBuilder> 
          getCommondFieldBuilder() {
        if (commondBuilder_ == null) {
          commondBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zx.demo.msg.ICommondMsg.ICmdMsg, com.zx.demo.msg.ICommondMsg.ICmdMsg.Builder, com.zx.demo.msg.ICommondMsg.ICmdMsgOrBuilder>(
                  getCommond(),
                  getParentForChildren(),
                  isClean());
          commond_ = null;
        }
        return commondBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.IMsg)
    }

    // @@protoc_insertion_point(class_scope:demo.IMsg)
    private static final com.zx.demo.msg.IMessage.IMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zx.demo.msg.IMessage.IMsg();
    }

    public static com.zx.demo.msg.IMessage.IMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IMsg>
        PARSER = new com.google.protobuf.AbstractParser<IMsg>() {
      @java.lang.Override
      public IMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zx.demo.msg.IMessage.IMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_IMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_IMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nIMsg.proto\022\004demo\032\rMsgType.proto\032\rIReqM" +
      "sg.Proto\032\016IRespMsg.Proto\032\rICmdMsg.Proto\"" +
      "\227\001\n\004IMsg\022\033\n\004type\030\001 \002(\0162\r.demo.MsgType\022\020\n" +
      "\010sequence\030\002 \002(\007\022\036\n\007request\030\003 \001(\0132\r.demo." +
      "IReqMsg\022 \n\010response\030\004 \001(\0132\016.demo.IRespMs" +
      "g\022\036\n\007commond\030\005 \001(\0132\r.demo.ICmdMsgB\033\n\017com" +
      ".zx.demo.msgB\010IMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zx.demo.msg.MessageType.getDescriptor(),
          com.zx.demo.msg.IRequestMsg.getDescriptor(),
          com.zx.demo.msg.IResponseMsg.getDescriptor(),
          com.zx.demo.msg.ICommondMsg.getDescriptor(),
        }, assigner);
    internal_static_demo_IMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_IMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_IMsg_descriptor,
        new java.lang.String[] { "Type", "Sequence", "Request", "Response", "Commond", });
    com.zx.demo.msg.MessageType.getDescriptor();
    com.zx.demo.msg.IRequestMsg.getDescriptor();
    com.zx.demo.msg.IResponseMsg.getDescriptor();
    com.zx.demo.msg.ICommondMsg.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
