// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IReqMsg.Proto

package com.zx.demo.msg;

public final class IRequestMsg {
  private IRequestMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IReqMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.IReqMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
     */
    boolean hasReqPlayer();
    /**
     * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
     */
    com.zx.demo.msg.CGReqPlayer.ReqPlayer getReqPlayer();
    /**
     * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
     */
    com.zx.demo.msg.CGReqPlayer.ReqPlayerOrBuilder getReqPlayerOrBuilder();
  }
  /**
   * Protobuf type {@code demo.IReqMsg}
   */
  public  static final class IReqMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.IReqMsg)
      IReqMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IReqMsg.newBuilder() to construct.
    private IReqMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IReqMsg() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IReqMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.zx.demo.msg.CGReqPlayer.ReqPlayer.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = reqPlayer_.toBuilder();
              }
              reqPlayer_ = input.readMessage(com.zx.demo.msg.CGReqPlayer.ReqPlayer.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reqPlayer_);
                reqPlayer_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zx.demo.msg.IRequestMsg.internal_static_demo_IReqMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zx.demo.msg.IRequestMsg.internal_static_demo_IReqMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zx.demo.msg.IRequestMsg.IReqMsg.class, com.zx.demo.msg.IRequestMsg.IReqMsg.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int REQPLAYER_FIELD_NUMBER = 2;
    private com.zx.demo.msg.CGReqPlayer.ReqPlayer reqPlayer_;
    /**
     * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
     */
    public boolean hasReqPlayer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
     */
    public com.zx.demo.msg.CGReqPlayer.ReqPlayer getReqPlayer() {
      return reqPlayer_ == null ? com.zx.demo.msg.CGReqPlayer.ReqPlayer.getDefaultInstance() : reqPlayer_;
    }
    /**
     * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
     */
    public com.zx.demo.msg.CGReqPlayer.ReqPlayerOrBuilder getReqPlayerOrBuilder() {
      return reqPlayer_ == null ? com.zx.demo.msg.CGReqPlayer.ReqPlayer.getDefaultInstance() : reqPlayer_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getReqPlayer());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getReqPlayer());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zx.demo.msg.IRequestMsg.IReqMsg)) {
        return super.equals(obj);
      }
      com.zx.demo.msg.IRequestMsg.IReqMsg other = (com.zx.demo.msg.IRequestMsg.IReqMsg) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasReqPlayer() == other.hasReqPlayer());
      if (hasReqPlayer()) {
        result = result && getReqPlayer()
            .equals(other.getReqPlayer());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasReqPlayer()) {
        hash = (37 * hash) + REQPLAYER_FIELD_NUMBER;
        hash = (53 * hash) + getReqPlayer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.IRequestMsg.IReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zx.demo.msg.IRequestMsg.IReqMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.IReqMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.IReqMsg)
        com.zx.demo.msg.IRequestMsg.IReqMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zx.demo.msg.IRequestMsg.internal_static_demo_IReqMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zx.demo.msg.IRequestMsg.internal_static_demo_IReqMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zx.demo.msg.IRequestMsg.IReqMsg.class, com.zx.demo.msg.IRequestMsg.IReqMsg.Builder.class);
      }

      // Construct using com.zx.demo.msg.IRequestMsg.IReqMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReqPlayerFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (reqPlayerBuilder_ == null) {
          reqPlayer_ = null;
        } else {
          reqPlayerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zx.demo.msg.IRequestMsg.internal_static_demo_IReqMsg_descriptor;
      }

      @java.lang.Override
      public com.zx.demo.msg.IRequestMsg.IReqMsg getDefaultInstanceForType() {
        return com.zx.demo.msg.IRequestMsg.IReqMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.zx.demo.msg.IRequestMsg.IReqMsg build() {
        com.zx.demo.msg.IRequestMsg.IReqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zx.demo.msg.IRequestMsg.IReqMsg buildPartial() {
        com.zx.demo.msg.IRequestMsg.IReqMsg result = new com.zx.demo.msg.IRequestMsg.IReqMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (reqPlayerBuilder_ == null) {
          result.reqPlayer_ = reqPlayer_;
        } else {
          result.reqPlayer_ = reqPlayerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zx.demo.msg.IRequestMsg.IReqMsg) {
          return mergeFrom((com.zx.demo.msg.IRequestMsg.IReqMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zx.demo.msg.IRequestMsg.IReqMsg other) {
        if (other == com.zx.demo.msg.IRequestMsg.IReqMsg.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasReqPlayer()) {
          mergeReqPlayer(other.getReqPlayer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zx.demo.msg.IRequestMsg.IReqMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zx.demo.msg.IRequestMsg.IReqMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.zx.demo.msg.CGReqPlayer.ReqPlayer reqPlayer_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.CGReqPlayer.ReqPlayer, com.zx.demo.msg.CGReqPlayer.ReqPlayer.Builder, com.zx.demo.msg.CGReqPlayer.ReqPlayerOrBuilder> reqPlayerBuilder_;
      /**
       * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
       */
      public boolean hasReqPlayer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
       */
      public com.zx.demo.msg.CGReqPlayer.ReqPlayer getReqPlayer() {
        if (reqPlayerBuilder_ == null) {
          return reqPlayer_ == null ? com.zx.demo.msg.CGReqPlayer.ReqPlayer.getDefaultInstance() : reqPlayer_;
        } else {
          return reqPlayerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
       */
      public Builder setReqPlayer(com.zx.demo.msg.CGReqPlayer.ReqPlayer value) {
        if (reqPlayerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reqPlayer_ = value;
          onChanged();
        } else {
          reqPlayerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
       */
      public Builder setReqPlayer(
          com.zx.demo.msg.CGReqPlayer.ReqPlayer.Builder builderForValue) {
        if (reqPlayerBuilder_ == null) {
          reqPlayer_ = builderForValue.build();
          onChanged();
        } else {
          reqPlayerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
       */
      public Builder mergeReqPlayer(com.zx.demo.msg.CGReqPlayer.ReqPlayer value) {
        if (reqPlayerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              reqPlayer_ != null &&
              reqPlayer_ != com.zx.demo.msg.CGReqPlayer.ReqPlayer.getDefaultInstance()) {
            reqPlayer_ =
              com.zx.demo.msg.CGReqPlayer.ReqPlayer.newBuilder(reqPlayer_).mergeFrom(value).buildPartial();
          } else {
            reqPlayer_ = value;
          }
          onChanged();
        } else {
          reqPlayerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
       */
      public Builder clearReqPlayer() {
        if (reqPlayerBuilder_ == null) {
          reqPlayer_ = null;
          onChanged();
        } else {
          reqPlayerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
       */
      public com.zx.demo.msg.CGReqPlayer.ReqPlayer.Builder getReqPlayerBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getReqPlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
       */
      public com.zx.demo.msg.CGReqPlayer.ReqPlayerOrBuilder getReqPlayerOrBuilder() {
        if (reqPlayerBuilder_ != null) {
          return reqPlayerBuilder_.getMessageOrBuilder();
        } else {
          return reqPlayer_ == null ?
              com.zx.demo.msg.CGReqPlayer.ReqPlayer.getDefaultInstance() : reqPlayer_;
        }
      }
      /**
       * <code>optional .demo.ReqPlayer reqPlayer = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.CGReqPlayer.ReqPlayer, com.zx.demo.msg.CGReqPlayer.ReqPlayer.Builder, com.zx.demo.msg.CGReqPlayer.ReqPlayerOrBuilder> 
          getReqPlayerFieldBuilder() {
        if (reqPlayerBuilder_ == null) {
          reqPlayerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zx.demo.msg.CGReqPlayer.ReqPlayer, com.zx.demo.msg.CGReqPlayer.ReqPlayer.Builder, com.zx.demo.msg.CGReqPlayer.ReqPlayerOrBuilder>(
                  getReqPlayer(),
                  getParentForChildren(),
                  isClean());
          reqPlayer_ = null;
        }
        return reqPlayerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.IReqMsg)
    }

    // @@protoc_insertion_point(class_scope:demo.IReqMsg)
    private static final com.zx.demo.msg.IRequestMsg.IReqMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zx.demo.msg.IRequestMsg.IReqMsg();
    }

    public static com.zx.demo.msg.IRequestMsg.IReqMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IReqMsg>
        PARSER = new com.google.protobuf.AbstractParser<IReqMsg>() {
      @java.lang.Override
      public IReqMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IReqMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IReqMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IReqMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zx.demo.msg.IRequestMsg.IReqMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_IReqMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_IReqMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rIReqMsg.Proto\022\004demo\032\017ReqPlayer.proto\"9" +
      "\n\007IReqMsg\022\n\n\002id\030\001 \002(\005\022\"\n\treqPlayer\030\002 \001(\013" +
      "2\017.demo.ReqPlayerB\036\n\017com.zx.demo.msgB\013IR" +
      "equestMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zx.demo.msg.CGReqPlayer.getDescriptor(),
        }, assigner);
    internal_static_demo_IReqMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_IReqMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_IReqMsg_descriptor,
        new java.lang.String[] { "Id", "ReqPlayer", });
    com.zx.demo.msg.CGReqPlayer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
