// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IRespMsg.Proto

package com.zx.demo.msg;

public final class IResponseMsg {
  private IResponseMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IRespMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.IRespMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required bool result = 1;</code>
     */
    boolean getResult();

    /**
     * <code>optional bytes error_description = 2;</code>
     */
    boolean hasErrorDescription();
    /**
     * <code>optional bytes error_description = 2;</code>
     */
    com.google.protobuf.ByteString getErrorDescription();

    /**
     * <code>required bool last_block = 3;</code>
     */
    boolean hasLastBlock();
    /**
     * <code>required bool last_block = 3;</code>
     */
    boolean getLastBlock();

    /**
     * <code>required fixed32 block_index = 4;</code>
     */
    boolean hasBlockIndex();
    /**
     * <code>required fixed32 block_index = 4;</code>
     */
    int getBlockIndex();

    /**
     * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
     */
    boolean hasPlayerInfo();
    /**
     * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
     */
    com.zx.demo.msg.GCPlayerInfo.PlayerInfo getPlayerInfo();
    /**
     * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
     */
    com.zx.demo.msg.GCPlayerInfo.PlayerInfoOrBuilder getPlayerInfoOrBuilder();
  }
  /**
   * Protobuf type {@code demo.IRespMsg}
   */
  public  static final class IRespMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.IRespMsg)
      IRespMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IRespMsg.newBuilder() to construct.
    private IRespMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IRespMsg() {
      result_ = false;
      errorDescription_ = com.google.protobuf.ByteString.EMPTY;
      lastBlock_ = false;
      blockIndex_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IRespMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errorDescription_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lastBlock_ = input.readBool();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              blockIndex_ = input.readFixed32();
              break;
            }
            case 42: {
              com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = playerInfo_.toBuilder();
              }
              playerInfo_ = input.readMessage(com.zx.demo.msg.GCPlayerInfo.PlayerInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(playerInfo_);
                playerInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zx.demo.msg.IResponseMsg.internal_static_demo_IRespMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zx.demo.msg.IResponseMsg.internal_static_demo_IRespMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zx.demo.msg.IResponseMsg.IRespMsg.class, com.zx.demo.msg.IResponseMsg.IRespMsg.Builder.class);
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>required bool result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool result = 1;</code>
     */
    public boolean getResult() {
      return result_;
    }

    public static final int ERROR_DESCRIPTION_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString errorDescription_;
    /**
     * <code>optional bytes error_description = 2;</code>
     */
    public boolean hasErrorDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes error_description = 2;</code>
     */
    public com.google.protobuf.ByteString getErrorDescription() {
      return errorDescription_;
    }

    public static final int LAST_BLOCK_FIELD_NUMBER = 3;
    private boolean lastBlock_;
    /**
     * <code>required bool last_block = 3;</code>
     */
    public boolean hasLastBlock() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool last_block = 3;</code>
     */
    public boolean getLastBlock() {
      return lastBlock_;
    }

    public static final int BLOCK_INDEX_FIELD_NUMBER = 4;
    private int blockIndex_;
    /**
     * <code>required fixed32 block_index = 4;</code>
     */
    public boolean hasBlockIndex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required fixed32 block_index = 4;</code>
     */
    public int getBlockIndex() {
      return blockIndex_;
    }

    public static final int PLAYERINFO_FIELD_NUMBER = 5;
    private com.zx.demo.msg.GCPlayerInfo.PlayerInfo playerInfo_;
    /**
     * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
     */
    public boolean hasPlayerInfo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
     */
    public com.zx.demo.msg.GCPlayerInfo.PlayerInfo getPlayerInfo() {
      return playerInfo_ == null ? com.zx.demo.msg.GCPlayerInfo.PlayerInfo.getDefaultInstance() : playerInfo_;
    }
    /**
     * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
     */
    public com.zx.demo.msg.GCPlayerInfo.PlayerInfoOrBuilder getPlayerInfoOrBuilder() {
      return playerInfo_ == null ? com.zx.demo.msg.GCPlayerInfo.PlayerInfo.getDefaultInstance() : playerInfo_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastBlock()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlockIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPlayerInfo()) {
        if (!getPlayerInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, errorDescription_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, lastBlock_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed32(4, blockIndex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getPlayerInfo());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, errorDescription_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, lastBlock_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, blockIndex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPlayerInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zx.demo.msg.IResponseMsg.IRespMsg)) {
        return super.equals(obj);
      }
      com.zx.demo.msg.IResponseMsg.IRespMsg other = (com.zx.demo.msg.IResponseMsg.IRespMsg) obj;

      boolean result = true;
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && (getResult()
            == other.getResult());
      }
      result = result && (hasErrorDescription() == other.hasErrorDescription());
      if (hasErrorDescription()) {
        result = result && getErrorDescription()
            .equals(other.getErrorDescription());
      }
      result = result && (hasLastBlock() == other.hasLastBlock());
      if (hasLastBlock()) {
        result = result && (getLastBlock()
            == other.getLastBlock());
      }
      result = result && (hasBlockIndex() == other.hasBlockIndex());
      if (hasBlockIndex()) {
        result = result && (getBlockIndex()
            == other.getBlockIndex());
      }
      result = result && (hasPlayerInfo() == other.hasPlayerInfo());
      if (hasPlayerInfo()) {
        result = result && getPlayerInfo()
            .equals(other.getPlayerInfo());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getResult());
      }
      if (hasErrorDescription()) {
        hash = (37 * hash) + ERROR_DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getErrorDescription().hashCode();
      }
      if (hasLastBlock()) {
        hash = (37 * hash) + LAST_BLOCK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getLastBlock());
      }
      if (hasBlockIndex()) {
        hash = (37 * hash) + BLOCK_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getBlockIndex();
      }
      if (hasPlayerInfo()) {
        hash = (37 * hash) + PLAYERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zx.demo.msg.IResponseMsg.IRespMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zx.demo.msg.IResponseMsg.IRespMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.IRespMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.IRespMsg)
        com.zx.demo.msg.IResponseMsg.IRespMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zx.demo.msg.IResponseMsg.internal_static_demo_IRespMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zx.demo.msg.IResponseMsg.internal_static_demo_IRespMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zx.demo.msg.IResponseMsg.IRespMsg.class, com.zx.demo.msg.IResponseMsg.IRespMsg.Builder.class);
      }

      // Construct using com.zx.demo.msg.IResponseMsg.IRespMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPlayerInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorDescription_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        lastBlock_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        blockIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (playerInfoBuilder_ == null) {
          playerInfo_ = null;
        } else {
          playerInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zx.demo.msg.IResponseMsg.internal_static_demo_IRespMsg_descriptor;
      }

      @java.lang.Override
      public com.zx.demo.msg.IResponseMsg.IRespMsg getDefaultInstanceForType() {
        return com.zx.demo.msg.IResponseMsg.IRespMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.zx.demo.msg.IResponseMsg.IRespMsg build() {
        com.zx.demo.msg.IResponseMsg.IRespMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zx.demo.msg.IResponseMsg.IRespMsg buildPartial() {
        com.zx.demo.msg.IResponseMsg.IRespMsg result = new com.zx.demo.msg.IResponseMsg.IRespMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorDescription_ = errorDescription_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastBlock_ = lastBlock_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.blockIndex_ = blockIndex_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (playerInfoBuilder_ == null) {
          result.playerInfo_ = playerInfo_;
        } else {
          result.playerInfo_ = playerInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zx.demo.msg.IResponseMsg.IRespMsg) {
          return mergeFrom((com.zx.demo.msg.IResponseMsg.IRespMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zx.demo.msg.IResponseMsg.IRespMsg other) {
        if (other == com.zx.demo.msg.IResponseMsg.IRespMsg.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasErrorDescription()) {
          setErrorDescription(other.getErrorDescription());
        }
        if (other.hasLastBlock()) {
          setLastBlock(other.getLastBlock());
        }
        if (other.hasBlockIndex()) {
          setBlockIndex(other.getBlockIndex());
        }
        if (other.hasPlayerInfo()) {
          mergePlayerInfo(other.getPlayerInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasResult()) {
          return false;
        }
        if (!hasLastBlock()) {
          return false;
        }
        if (!hasBlockIndex()) {
          return false;
        }
        if (hasPlayerInfo()) {
          if (!getPlayerInfo().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zx.demo.msg.IResponseMsg.IRespMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zx.demo.msg.IResponseMsg.IRespMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean result_ ;
      /**
       * <code>required bool result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public Builder setResult(boolean value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString errorDescription_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes error_description = 2;</code>
       */
      public boolean hasErrorDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes error_description = 2;</code>
       */
      public com.google.protobuf.ByteString getErrorDescription() {
        return errorDescription_;
      }
      /**
       * <code>optional bytes error_description = 2;</code>
       */
      public Builder setErrorDescription(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes error_description = 2;</code>
       */
      public Builder clearErrorDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorDescription_ = getDefaultInstance().getErrorDescription();
        onChanged();
        return this;
      }

      private boolean lastBlock_ ;
      /**
       * <code>required bool last_block = 3;</code>
       */
      public boolean hasLastBlock() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool last_block = 3;</code>
       */
      public boolean getLastBlock() {
        return lastBlock_;
      }
      /**
       * <code>required bool last_block = 3;</code>
       */
      public Builder setLastBlock(boolean value) {
        bitField0_ |= 0x00000004;
        lastBlock_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool last_block = 3;</code>
       */
      public Builder clearLastBlock() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastBlock_ = false;
        onChanged();
        return this;
      }

      private int blockIndex_ ;
      /**
       * <code>required fixed32 block_index = 4;</code>
       */
      public boolean hasBlockIndex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required fixed32 block_index = 4;</code>
       */
      public int getBlockIndex() {
        return blockIndex_;
      }
      /**
       * <code>required fixed32 block_index = 4;</code>
       */
      public Builder setBlockIndex(int value) {
        bitField0_ |= 0x00000008;
        blockIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 block_index = 4;</code>
       */
      public Builder clearBlockIndex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        blockIndex_ = 0;
        onChanged();
        return this;
      }

      private com.zx.demo.msg.GCPlayerInfo.PlayerInfo playerInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Builder, com.zx.demo.msg.GCPlayerInfo.PlayerInfoOrBuilder> playerInfoBuilder_;
      /**
       * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
       */
      public boolean hasPlayerInfo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
       */
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo getPlayerInfo() {
        if (playerInfoBuilder_ == null) {
          return playerInfo_ == null ? com.zx.demo.msg.GCPlayerInfo.PlayerInfo.getDefaultInstance() : playerInfo_;
        } else {
          return playerInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
       */
      public Builder setPlayerInfo(com.zx.demo.msg.GCPlayerInfo.PlayerInfo value) {
        if (playerInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          playerInfo_ = value;
          onChanged();
        } else {
          playerInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
       */
      public Builder setPlayerInfo(
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Builder builderForValue) {
        if (playerInfoBuilder_ == null) {
          playerInfo_ = builderForValue.build();
          onChanged();
        } else {
          playerInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
       */
      public Builder mergePlayerInfo(com.zx.demo.msg.GCPlayerInfo.PlayerInfo value) {
        if (playerInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              playerInfo_ != null &&
              playerInfo_ != com.zx.demo.msg.GCPlayerInfo.PlayerInfo.getDefaultInstance()) {
            playerInfo_ =
              com.zx.demo.msg.GCPlayerInfo.PlayerInfo.newBuilder(playerInfo_).mergeFrom(value).buildPartial();
          } else {
            playerInfo_ = value;
          }
          onChanged();
        } else {
          playerInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
       */
      public Builder clearPlayerInfo() {
        if (playerInfoBuilder_ == null) {
          playerInfo_ = null;
          onChanged();
        } else {
          playerInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
       */
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Builder getPlayerInfoBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getPlayerInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
       */
      public com.zx.demo.msg.GCPlayerInfo.PlayerInfoOrBuilder getPlayerInfoOrBuilder() {
        if (playerInfoBuilder_ != null) {
          return playerInfoBuilder_.getMessageOrBuilder();
        } else {
          return playerInfo_ == null ?
              com.zx.demo.msg.GCPlayerInfo.PlayerInfo.getDefaultInstance() : playerInfo_;
        }
      }
      /**
       * <code>optional .demo.PlayerInfo playerInfo = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zx.demo.msg.GCPlayerInfo.PlayerInfo, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Builder, com.zx.demo.msg.GCPlayerInfo.PlayerInfoOrBuilder> 
          getPlayerInfoFieldBuilder() {
        if (playerInfoBuilder_ == null) {
          playerInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zx.demo.msg.GCPlayerInfo.PlayerInfo, com.zx.demo.msg.GCPlayerInfo.PlayerInfo.Builder, com.zx.demo.msg.GCPlayerInfo.PlayerInfoOrBuilder>(
                  getPlayerInfo(),
                  getParentForChildren(),
                  isClean());
          playerInfo_ = null;
        }
        return playerInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.IRespMsg)
    }

    // @@protoc_insertion_point(class_scope:demo.IRespMsg)
    private static final com.zx.demo.msg.IResponseMsg.IRespMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zx.demo.msg.IResponseMsg.IRespMsg();
    }

    public static com.zx.demo.msg.IResponseMsg.IRespMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IRespMsg>
        PARSER = new com.google.protobuf.AbstractParser<IRespMsg>() {
      @java.lang.Override
      public IRespMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IRespMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IRespMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IRespMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zx.demo.msg.IResponseMsg.IRespMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_IRespMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_IRespMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016IRespMsg.Proto\022\004demo\032\020PlayerInfo.proto" +
      "\"\204\001\n\010IRespMsg\022\016\n\006result\030\001 \002(\010\022\031\n\021error_d" +
      "escription\030\002 \001(\014\022\022\n\nlast_block\030\003 \002(\010\022\023\n\013" +
      "block_index\030\004 \002(\007\022$\n\nplayerInfo\030\005 \001(\0132\020." +
      "demo.PlayerInfoB\037\n\017com.zx.demo.msgB\014IRes" +
      "ponseMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zx.demo.msg.GCPlayerInfo.getDescriptor(),
        }, assigner);
    internal_static_demo_IRespMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_IRespMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_IRespMsg_descriptor,
        new java.lang.String[] { "Result", "ErrorDescription", "LastBlock", "BlockIndex", "PlayerInfo", });
    com.zx.demo.msg.GCPlayerInfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
